# Generated by Django 6.1.1 on 2026-09-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ats', models.CharField(blank=True, max_length=32, null=True)),
                ('board_token', models.CharField(blank=True, max_length=255, null=True)),
                ('vetted_on', models.DateField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('company_url', models.URLField(blank=True, default='', max_length=500)),
                ('glassdoor_url', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('legal_flags', models.JSONField(blank=True, default=dict)),
                ('prior_rejections', models.PositiveIntegerField(default=0)),
                ('application_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('scoring', models.JSONField(blank=True, default=dict)),
                ('fit_score', models.FloatField(blank=True, null=True)),
                ('vetting_record', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'indexes': [models.Index(fields=['vetted_on'], name='crawler_com_vetted__0425c8_idx'), models.Index(fields=['fit_score'], name='crawler_com_fit_sco_3636d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('ats', 'board_token'), name='unique_board')],
            },
        ),
        migrations.CreateModel(
            name='CrawledPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('departments', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('ats_updated_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('fit_score', models.FloatField(blank=True, null=True)),
                ('emailed_on', models.DateField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='crawler.company')),
            ],
            options={
                'indexes': [models.Index(fields=['fit_score'], name='crawler_cra_fit_sco_57c31c_idx'), models.Index(fields=['emailed_on'], name='crawler_cra_emailed_f33e64_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'external_id'), name='unique_posting_per_company')],
            },
        ),
    ]
