# Generated by Django 6.1.1 on 2026-10-06 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('edition', models.CharField(blank=True, max_length=200)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCompanyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='crawler.referencesource')),
            ],
            options={
                'verbose_name_plural': 'reference company entries',
                'ordering': ['source', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceStateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('rating', models.CharField(max_length=100)),
                ('scoring_bucket', models.CharField(blank=True, max_length=20)),
                ('tally', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='crawler.referencesource')),
            ],
            options={
                'verbose_name_plural': 'reference state entries',
                'ordering': ['source', 'state'],
                'constraints': [models.UniqueConstraint(fields=('source', 'state'), name='uniq_state_per_source')],
            },
        ),
    ]
