# Generated by Django 6.1.1 on 2026-10-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_referencesource_referencecompanyentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('purpose', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_creation_input_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_input_tokens', models.PositiveIntegerField(default=0)),
                ('web_search_requests', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('stop_reason', models.CharField(blank=True, max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'LLM call audit',
                'verbose_name_plural': 'LLM call audits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', 'created_at'], name='crawler_llm_purpose_24f2ff_idx')],
            },
        ),
    ]
